[[ build.env ]]
  name = 'BP_DOTNET_FRAMEWORK_VERSION'
  value = '3.1.21'
[[ build.env ]]
  name = 'BP_DOTNET_PROJECT_PATH'
  value = './src/aspnet'
[[ build.env ]]
  name = 'BPE_ASPNETCORE_FORWARDEDHEADERS_ENABLED'
  value = 'true'
